custombucket = "guru-destinationtxt"
table = "intellipaat"
databasehost = "intellipaat.c5yoesau2sbt.us-east-1.rds.amazonaws.com"
duser = "intel"
dpass = "intel123"
s3database = "intellipaat"
kapp = "http://10.0.141.236:31046/"
