custombucket = "guru-destinationtxt"
table = "intellipaat"
databasehost = "intellipaat.czww0kw26qcu.us-west-2.rds.amazonaws.com"
duser = "intel"
dpass = "intel123"
s3database = "intellipaat"
kapp = "http://3.228.220.21/"
